api = "0.2"

[buildpack]
id = "heroku-gerbil/gerbil"
name = "Gerbil"
version = "0.3"
homepage = "https://github.com/heroku-gerbil/heroku-buildpack-gerbil"
gerbil_version = "v0.18.1"

[[publish.Vendor]]
url = "https://github.com/heroku-gerbil/heroku-buildpack-gerbil/archive/refs/tags/v0.3.tar.gz"
dir = "vendor/ruby/heroku-22"

[publish.Ignore]
files = [
  ".gitignore",
  ".github",
]

[[stacks]]
id = "heroku-22"

[metadata]

[metadata.release]
